config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  root 'pictures#index'
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :favorites, only: [:index, :create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
  validates :title, presence: true
  validates :content, presence: true
  validates :content, length: { in: 1..1000 }
  validates :image, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :name, presence: true
  validates :email, presence: true
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorites.all
  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end
  
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[ show edit update destroy ]

  def index
    @pictures = Picture.all
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  def edit
    if @picture.id != current_user.id
      redirect_to pictures_path
    end
  end

  def create
    @picture = current_user.pictures.build(picture_params)

    respond_to do |format|
      if @picture.save
        ConfirmMailer.confirm_mail(@picture).deliver
        format.html { redirect_to @picture, notice: "Picture was successfully created." }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: "Picture was successfully updated." }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: "Picture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:title, :content, :image, :image_cache, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :set_user, only: %i[ show edit update ]

  def new
    @user = User.new
  end

  def edit
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def update
    if @user.update(user_edit_params)
      redirect_to user_path, notice: "ユーザー情報を編集しました"
    else
      render :edit
    end
  end

  def show
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def user_edit_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<h1 class="insta_f2 text-center"><span class="material-icons favorite">favorite</span>Favorites</h1>

<ul class="picture_list row">
<% if @favorites.size != 0 %>
  <% @favorites.each do |favorite| %>
    <li class="col-sm-12 col-md-8 col-md-offset-2">
      <div class="upper flex">
        <p class="item"><span class="material-icons camera">camera_enhance</span><span class="heading">User: <%= favorite.picture.user.name %></span></p>
        <p class="btn_block item">
          <span class="material-icons">important_devices</span><%= link_to 'Show', picture_url(favorite.picture.id) %>
          <% if favorite.picture.user_id == current_user.id %>
            <span class="material-icons">edit</span><%= link_to 'Edit', edit_picture_path(favorite.picture.id), data: { confirm: '本当に編集していいですか？' } %>
            <span class="material-icons">delete</span><%= link_to 'Destroy', picture_path(favorite.picture.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %>
          <% end %>
        </p>
      </div>
      <p><%= image_tag favorite.picture.image.url %></p>
      <div class="lower">
        <p><span class="heading">Title:</span><%= favorite.picture.title %></p>
        <p class="content"><span class="heading">Content:</span><%= favorite.picture.content %></p>
      </div>
    </li>
  <% end %>
<% else %>
    <li class="col-sm-12 col-md-8 col-md-offset-2">
      <div class="upper flex">
        <p>お気に入り登録はまだありません。</p>
      </div>
    </li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key} flash_message alert alert-info") %>
      <% end %>
      <header class="row">
        <nav class="navbar navbar-default  col-sm-12 col-md-10 col-md-offset-1">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
                <span class="sr-only insta_f1">InstagramClone</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand insta_f1" href="#">InstagramClone</a>
            </div>
            <div id="gnavi" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <% if logged_in? %>
                  <li><%= link_to "プロフィール", user_path(current_user.id) %></li>
                  <li><%= link_to "写真一覧", pictures_path %></li>
                  <li><%= link_to "お気に入り", favorites_path %></li>
                  <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
                <% else %>
                  <li><%= link_to "新規登録", new_user_path %></li>
                  <li><%= link_to "ログイン", new_session_path %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url:choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(picture.errors.count, "件") %> のエラーがあります。</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <ul class="picture_list row">
    <li class="col-sm-12 col-md-10 col-md-offset-1 form">
      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
      </div>

      <div class="field">
        <%= form.label :content %>
        <%= form.text_area :content %>
      </div>

      <div class="field">
        <%= form.label :image %>
        <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
        <%= form.file_field :image %>
        <%= form.hidden_field :image_cache %>
      </div>
    </li>
  </ul>

  <div class="actions text-center">
    <%= form.submit :class => "submit btn btn-info btn-lg" %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h1 class="text-center">確認画面</h1>

<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <ul class="picture_list row">
    <li class="col-sm-12 col-md-10 col-md-offset-1 form">
      <div class="field">
        <p class="label">Title:</p>
        <p><%= @picture.title %></p>
      </div>

      <div class="field">
        <p class="label">Content:</p>
        <p class="content"><%= @picture.content %></p>
      </div>

      <div class="field">
        <p class="label">Image:</p>
        <p><%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %></p>
      </div>
      <%= form.hidden_field :image_cache %>
    </li>
  </ul>

  <div class="action text-center">
    <%= form.submit "投稿する", class: "submit btn btn-info btn-lg" %>
  </div>



<% end %>

<div class="text-center picture_show bottom_btn_block">
  <%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
    <%= form.hidden_field :image_cache %>
    <span class="material-icons">reply</span><%= form.submit "戻る", name: "back", class: "submit btn btn-info" %>
  <% end %>
</div>

app/views/pictures/edit.html.erb
<h1 class="insta_f2 text-center">Editing Picture</h1>

<%= render 'form', picture: @picture %>


<div class="text-center picture_show bottom_btn_block">
  <% if @picture.user_id == current_user.id %>
    <span class="material-icons">important_devices</span><%= link_to 'Show', @picture %>  |
  <% end %>
    <span class="material-icons">reply</span><%= link_to 'Back', pictures_path %>
</div>

app/views/pictures/index.html.erb
<p class="text-center"><%= link_to '投稿する', new_picture_path, class: "submit btn btn-info btn-lg" %></p>
<h1 class="insta_f2 text-center">Pictures</h1>

<ul class="picture_list row">
<% @pictures.each do |picture| %>
  <li class="col-sm-12 col-md-8 col-md-offset-2">
    <div class="upper flex">
      <p class="item"><span class="material-icons camera">camera_enhance</span><span class="heading">User: <%= picture.user.name %></span></p>
      <p class="btn_block item">
        <span class="material-icons">important_devices</span><%= link_to 'Show', picture %>
        <% if picture.user_id == current_user.id %>
          <span class="material-icons">edit</span><%= link_to 'Edit', edit_picture_path(picture.id), data: { confirm: '本当に編集していいですか？' } %>
          <span class="material-icons">delete</span><%= link_to 'Destroy', picture_path(picture.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %>
        <% end %>
      </p>
    </div>
    <p><%= image_tag picture.image.url %></p>
    <div class="lower">
      <p><span class="heading">Title:</span><%= picture.title %></p>
      <p class="content"><span class="heading">Content:</span><%= picture.content %></p>
    </div>
  </li>
<% end %>
</ul>

app/views/pictures/new.html.erb
<h1 class="insta_f2 text-center">New Picture</h1>

<%= render 'form', picture: @picture %>

<div class="text-center picture_show bottom_btn_block">
    <span class="material-icons">reply</span><%= link_to 'Back', pictures_path %>
</div>

app/views/pictures/show.html.erb
<ul class="picture_list row">
  <li class="col-sm-12 col-md-10 col-md-offset-1">
    <div class="upper flex">
      <p class="item"><span class="material-icons camera">camera_enhance</span><span class="heading">User: <%= @picture.user.name %></span></p>
      <p class="btn_block item">
        <% unless @picture.user_id == current_user.id %>
          <% if @favorite.present? %>
            <span class="material-icons favorite">favorite</span><%= link_to 'お気に入りを解除する', favorite_path(id: @favorite.id), method: :delete %>
          <% else %>
            <span class="material-icons favorite_border">favorite_border</span><%= link_to 'お気に入りにする', favorites_path(picture_id: @picture.id), method: :post %>
          <% end %>
        <% end %>
      </p>
    </div>
    <p><%= image_tag @picture.image.url %></p>
    <div class="lower">
      <p><span class="heading">Title:</span><%= @picture.title %></p>
      <p class="content"><span class="heading">Content:</span><%= @picture.content %></p>
    </div>
  </li>
</ul>

<div class="text-center picture_show bottom_btn_block">
  <% if @picture.user_id == current_user.id %>
    <span class="material-icons">edit</span><%= link_to 'Edit', edit_picture_path(@picture) %>  |
  <% end %>
    <span class="material-icons">reply</span><%= link_to 'Back', pictures_path %>
</div>

app/views/users/edit.html.erb
<article class="user_page edit col-sm-12 col-md-8 col-md-offset-2">
  <h1>プロフィール 編集</h1>

  <%= form_with(model: @user, local: true, url:user_path) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation" class="alert alert-info text-center">
        <p class="fw_b"><%= pluralize(@user.errors.count, "件") %> のエラーがあります。</p>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>

    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>

    <div class="field">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
    </div>

    <div class="field">
      <%= form.label :image %>
      <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
    </div>

    <div class="actions">
      <%= form.submit '編集する', data: { confirm: '本当に編集していいですか？' }, class: "submit btn btn-primary btn-lg" %>
    </div>
  <% end %>

  <p class="text-center back"><%= link_to 'プロフィールへ戻る', @user, class: "submit btn btn-primary btn-lg" %></p>
</article>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<article class="sign_form col-sm-12 col-md-6 col-md-offset-3">
  <h1 class="text-center insta_f2">Sign up</h1>
  <%= form_with(model: @user, local: true) do |f| %>
    <p><%= f.label :name %>
    <%= f.text_field :name %></p>
    <p><%= f.label :email %>
    <%= f.email_field :email %></p>
    <p><%= f.label :password %>
    <%= f.password_field :password %></p>
    <p><%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %></p>
    <p class="text-center"><%= f.submit "新規登録する", class: "submit btn btn-primary btn-lg" %></p>
  <% end %>
</article>

app/views/users/show.html.erb
<article class="user_page col-sm-12 col-md-8 col-md-offset-2 text-center">
  <h1><%= @user.name %>のページ</h1>
  <p><span>メールアドレス:</span><%= @user.email %></p>
  <p><span>プロフィール画像:</span>
    <% if @user.image.url != nil %>
    <%= image_tag @user.image.url %>
    <% else %>
    まだ登録されていません
    <% end %>
  </p>
  <% if @user.id == current_user.id %>
    <%= link_to '編集画面へ', edit_user_path(@user), class: "submit btn btn-primary btn-lg" %>
  <% end %>
</article>